# Generated by Django 4.2.3 on 2023-10-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='amount',
            new_name='spendings',
        ),
    ]
