# Generated by Django 4.2.3 on 2023-10-04 04:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('income', '0002_budget'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Budget',
            new_name='Income',
        ),
    ]
